spring.application.name=config-server


#eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.server.git.uri=https://github.com/sonukumar0109/application_config/
